<?php

namespace Atrox\Haikunator;

class Haikunator
{
    public static $ADJECTIVES = [
        "adorable",
        "aluminum",
        "ancient",
        "azure",
        "billowing",
        "blue",
        "bold",
        "brave",
        "brilliant",
        "broad",
        "bubbly",
        "calm",
        "careful",
        "cerulean",
        "citrine",
        "clever",
        "cool",
        "copper",
        "crystal",
        "curly",
        "cyan",
        "dark",
        "dawn",
        "delicate",
        "delightful",
        "dry",
        "eager",
        "effervescent",
        "elegant",
        "emerald",
        "fancy",
        "fizzy",
        "floral",
        "fragrant",
        "frosty",
        "gentle",
        "gifted",
        "glamorous",
        "gray",
        "green",
        "handsome",
        "helpful",
        "icy",
        "intriguing",
        "jeweled",
        "jolly",
        "keen",
        "kind",
        "lingering",
        "lively",
        "lucky",
        "magenta",
        "mauve",
        "melodic",
        "misty",
        "noisy",
        "odd",
        "orange",
        "patient",
        "peachy",
        "periwinkle",
        "platinum",
        "polished",
        "proud",
        "purple",
        "quaint",
        "quiet",
        "rapid",
        "restless",
        "ringing",
        "round",
        "royal",
        "shy",
        "silent",
        "silly",
        "silver",
        "small",
        "snowy",
        "soft",
        "solitary",
        "sparkling",
        "square",
        "steep",
        "steep",
        "still",
        "sweet",
        "tiny",
        "triangular",
        "twilight",
        "ubiquitous",
        "utopian",
        "valiant",
        "verdant",
        "versed",
        "vexing",
        "wandering",
        "warm",
        "weathered",
        "whispering",
        "wild",
        "wispy",
        "xanthous",
        "young",
        "zany",
        "zesty",
        "zippy",
    ];

    public static $NOUNS = [
        "aardvark",
        "albatross",
        "alpaca",
        "anaconda",
        "antlion",
        "atom",
        "basilisk",
        "beetle",
        "bobcat",
        "breeze",
        "brook",
        "butterfly",
        "cake",
        "camel",
        "capybara",
        "cardinal",
        "caribou",
        "catamaran",
        "caterpillar",
        "catfish",
        "chameleon",
        "cheetah",
        "cherry",
        "chinchilla",
        "chipmunk",
        "cloud",
        "condor",
        "coyote",
        "crane",
        "crocodile",
        "crow",
        "daffodil",
        "dandelion",
        "darkness",
        "dawn",
        "dew",
        "dolphin",
        "dove",
        "dream",
        "dust",
        "eagle",
        "elephant",
        "elk",
        "falcon",
        "feather",
        "field",
        "firefly",
        "flamingo",
        "fog",
        "forest",
        "fox",
        "frog",
        "frost",
        "gazelle",
        "gecko",
        "giraffe",
        "glade",
        "grass",
        "haze",
        "heart",
        "hedgehog",
        "hill",
        "ibex",
        "jaguar",
        "kangaroo",
        "kiwi",
        "koala",
        "koi",
        "ladybug",
        "lake",
        "leaf",
        "lemur",
        "lightning",
        "lilac",
        "lion",
        "llama",
        "lynx",
        "lyrebird",
        "macaw",
        "mantis",
        "marigold",
        "marlin",
        "meadow",
        "mockingbird",
        "moon",
        "moose",
        "moth",
        "mountain",
        "mouse",
        "narwhal",
        "newt",
        "night",
        "ocean",
        "ocelot",
        "otter",
        "owl",
        "panda",
        "parrot",
        "pearl",
        "penguin",
        "piano",
        "pine",
        "pond",
        "quail",
        "rain",
        "raven",
        "rhinoceros",
        "river",
        "salamander",
        "sea",
        "seahorse",
        "shadow",
        "sky",
        "smoke",
        "snowflake",
        "spring",
        "star",
        "starling",
        "sun",
        "sunflower",
        "sunset",
        "tapir",
        "thunder",
        "tiger",
        "tree",
        "tulip",
        "turtle",
        "uguisu",
        "violet",
        "wallaby",
        "walrus",
        "waterfall",
        "wave",
        "whale",
        "wolf",
        "wren",
        "yak",
        "zebra",
    ];

    /**
     * Generate Heroku-like random names to use in your applications.
     * @param array $params
     * @return string
     */
    public static function haikunate(array $params = array())
    {
        $defaults = [
            "delimiter" => "-",
            "tokenLength" => 4,
            "tokenHex" => false,
            "tokenChars" => "0123456789",
        ];

        $params = array_merge($defaults, $params);

        if ($params["tokenHex"] == true) $params["tokenChars"] = "0123456789abcdef";

        $adjective = self::$ADJECTIVES[mt_rand(0, count(self::$ADJECTIVES) - 1)];
        $noun = self::$NOUNS[mt_rand(0, count(self::$NOUNS) - 1)];
        $token = "";

        for($i = 0; $i <= $params["tokenLength"] - 1; $i++)
        {
            $token .= $params["tokenChars"][mt_rand(0, strlen($params["tokenChars"])-1)];
        }

        $sections = [$adjective, $noun, $token];
        return implode($params["delimiter"], array_filter($sections));
    }
}
